# Generated by Django 5.2.7 on 2025-10-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydresscode', '0003_usuario_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(max_length=128),
        ),
    ]
