# Generated by Django 5.2.1 on 2025-10-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydresscode', '0005_alter_usuario_contrasena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(max_length=129),
        ),
    ]
