# Generated by Django 5.2.7 on 2025-10-17 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydresscode', '0007_prenda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prenda',
        ),
    ]
