# Generated by Django 5.2.7 on 2025-10-17 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydresscode', '0008_delete_prenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armario',
            fields=[
                ('idPrenda', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=50)),
                ('imagen', models.CharField(max_length=255)),
                ('temporada', models.CharField(blank=True, max_length=40)),
                ('estilo', models.CharField(blank=True, max_length=60)),
                ('clasificacion', models.CharField(blank=True, max_length=60)),
                ('esFavorito', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('idUsuario', models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='prendas', to='mydresscode.usuario')),
            ],
            options={
                'db_table': 'armario',
                'ordering': ['-fecha'],
            },
        ),
    ]
