# Generated by Django 5.2.7 on 2025-10-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydresscode', '0009_armario'),
    ]

    operations = [
        migrations.AddField(
            model_name='armario',
            name='imagen_segmentada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
