# Generated by Django 5.2.7 on 2025-11-12 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydresscode', '0010_armario_imagen_segmentada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('idOutfit', models.AutoField(primary_key=True, serialize=False)),
                ('estilo', models.CharField(max_length=45)),
                ('clima_recomendado', models.CharField(max_length=45)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('esFavorito', models.BooleanField(default=False)),
                ('idUsuario', models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.CASCADE, to='mydresscode.usuario')),
            ],
            options={
                'db_table': 'outfit',
            },
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('idRecomendacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('clima_del_dia', models.CharField(max_length=45)),
                ('valoracion', models.CharField(max_length=45)),
                ('idOutfit', models.ForeignKey(db_column='idOutfit', on_delete=django.db.models.deletion.CASCADE, to='mydresscode.outfit')),
                ('idUsuario', models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.CASCADE, to='mydresscode.usuario')),
            ],
            options={
                'db_table': 'recomendacion',
            },
        ),
        migrations.CreateModel(
            name='VerPrenda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen_url', models.TextField()),
                ('tipo_prenda', models.TextField()),
                ('outfit', models.ForeignKey(db_column='outfit_id', on_delete=django.db.models.deletion.CASCADE, related_name='ver_prendas', to='mydresscode.outfit')),
            ],
            options={
                'db_table': 'ver_prenda',
            },
        ),
    ]
