# Generated by Django 4.2 on 2025-11-15 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydresscode', '0011_outfit_recomendacion'),
        ('mydresscode', '0011_outfit_recomendacion_verprenda'),
    ]

    operations = [
    ]
