# Generated by Django 4.1.7 on 2025-11-15 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydresscode', '0012_merge_20251115_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(db_column='id_Usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mydresscode.usuario')),
                ('nombre_completo', models.CharField(blank=True, db_column='nombre_completo', max_length=100, null=True)),
                ('talla_superior', models.CharField(blank=True, max_length=20, null=True)),
                ('talla_inferior', models.CharField(blank=True, max_length=20, null=True)),
                ('talla_calzado', models.CharField(blank=True, max_length=20, null=True)),
                ('estilos', models.JSONField(blank=True, db_column='estilos_fav', default=list)),
                ('colores_fav', models.JSONField(blank=True, default=list)),
                ('temporadas_fav', models.JSONField(blank=True, db_column='temporadas_fav', default=list)),
                ('config_completada', models.BooleanField(db_column='config_completada', default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizado_en')),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuarios',
                'db_table': 'perfil_usuario',
            },
        ),
    ]
