# Generated by Django 4.2.7 on 2025-11-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydresscode', '0013_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacion',
            name='valoracion',
            field=models.IntegerField(),
        ),
    ]
